# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - arm_controller

  arm_controller:
    type: FollowJointTrajectory
    joints:
      - base_link_joint
      - shoulder_link_joint
      - elbow_link_joint
      - wrist_link_joint
      - palm_link_joint
      - left_finger_link_joint
      - right_finger_link_joint
    action_ns: follow_joint_trajectory
    default: true